package cardboardcommunity;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.LayoutManager;
import java.util.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rnkambara
 */
public class BasePanel extends javax.swing.JPanel {

    /**
     * Creates new form BasePanel
     */
    public BasePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        scrollPane1 = new java.awt.ScrollPane();
        panelScrollBox = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        collectionButton = new java.awt.Button();
        homeButton = new java.awt.Button();
        eventButton = new java.awt.Button();
        groupButton = new java.awt.Button();
        panel1 = new java.awt.Panel();
        labelCardboardCommunity = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cardboardCommunityIcon = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        cbcIcon = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setBackground(new java.awt.Color(101, 95, 123));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(250, 240, 231));

        panelScrollBox.setBackground(new java.awt.Color(254, 254, 254));
        panelScrollBox.setForeground(new java.awt.Color(254, 254, 254));
        panelScrollBox.setAlignmentX(0.0F);

        javax.swing.GroupLayout panelScrollBoxLayout = new javax.swing.GroupLayout(panelScrollBox);
        panelScrollBox.setLayout(panelScrollBoxLayout);
        panelScrollBoxLayout.setHorizontalGroup(
            panelScrollBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
        );
        panelScrollBoxLayout.setVerticalGroup(
            panelScrollBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );

        scrollPane1.add(panelScrollBox);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 1030, 510));

        jPanel2.setBackground(new java.awt.Color(250, 240, 231));

        collectionButton.setActionCommand("collectionButton");
        collectionButton.setBackground(new java.awt.Color(101, 95, 123));
        collectionButton.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        collectionButton.setForeground(new java.awt.Color(254, 254, 254));
        collectionButton.setLabel("Collections");

        homeButton.setActionCommand("homeButton");
        homeButton.setBackground(new java.awt.Color(101, 95, 123));
        homeButton.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(254, 254, 254));
        homeButton.setLabel("Home");

        eventButton.setActionCommand("eventButton");
        eventButton.setBackground(new java.awt.Color(101, 95, 123));
        eventButton.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        eventButton.setForeground(new java.awt.Color(254, 254, 254));
        eventButton.setLabel("Events");

        groupButton.setActionCommand("groupButton");
        groupButton.setBackground(new java.awt.Color(101, 95, 123));
        groupButton.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        groupButton.setForeground(new java.awt.Color(254, 254, 254));
        groupButton.setLabel("Groups");
        groupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eventButton, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(groupButton, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(collectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(eventButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(groupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(collectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        collectionButton.getAccessibleContext().setAccessibleName("collectionButton");
        eventButton.getAccessibleContext().setAccessibleName("eventButton");
        groupButton.getAccessibleContext().setAccessibleName("groupButton");

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 180, 510));

        panel1.setBackground(new java.awt.Color(250, 240, 231));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCardboardCommunity.setFont(new java.awt.Font("Ubuntu Condensed", 0, 48)); // NOI18N
        labelCardboardCommunity.setForeground(new java.awt.Color(101, 95, 123));
        labelCardboardCommunity.setText("Cardboard Community");
        panel1.add(labelCardboardCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(101, 95, 123));
        panel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 223, 538, 12));
        panel1.add(cardboardCommunityIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 71, -1, 193));

        jSeparator2.setBackground(new java.awt.Color(101, 95, 123));
        panel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 241, 538, -1));
        panel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 450, 10));

        cbcIcon.setIcon(new javax.swing.ImageIcon("/home/rnkambara/Documents/CardBoard-Community/images/cardboard_community.png")); // NOI18N
        panel1.add(cbcIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));
        panel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 450, 10));
        panel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 450, 20));
        panel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 450, 20));

        add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 1210, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void groupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_groupButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cardboardCommunityIcon;
    private javax.swing.JLabel cbcIcon;
    private java.awt.Button collectionButton;
    private java.awt.Button eventButton;
    private java.awt.Button groupButton;
    private java.awt.Button homeButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel labelCardboardCommunity;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private java.awt.Panel panel1;
    private javax.swing.JPanel panelScrollBox;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
