package cardboardcommunity;
import java.sql.SQLException;
import java.util.Collection;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Component; 
import javax.swing.JButton;
import javax.swing.JToolBar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rnkambara
 */
public class BasePanel extends javax.swing.JPanel {

    /**
     * Creates new form BasePanel
     */
    public BasePanel() {
        initComponents();
    }
    
    public void fillScrollableArea(Collection<Component> panels)
    {
        scrollPanelBox.removeAll();
        if(panels != null)
        {
          for(Component panel : panels)
          {
            scrollPanelBox.add(panel);
            scrollPanelBox.add(new JToolBar.Separator());
          }
        }
    	CardboardCommunity.form.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        scrollPanelBox = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        homeButton = new java.awt.Button();
        eventButton = new java.awt.Button();
        groupButton = new java.awt.Button();
        collectionButton = new java.awt.Button();
        jPanel3 = new javax.swing.JPanel();
        globalRatings = new java.awt.Button();
        groupCollection = new java.awt.Button();
        recommendedGames = new java.awt.Button();
        gameNightRecommendation = new java.awt.Button();
        userComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        labelCardboardCommunity = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cardboardCommunityIcon = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        cbcIcon = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setBackground(new java.awt.Color(101, 95, 123));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(250, 240, 231));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        scrollPanelBox.setBackground(new java.awt.Color(254, 254, 254));
        scrollPanelBox.setLayout(new javax.swing.BoxLayout(scrollPanelBox, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(scrollPanelBox);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 1020, 620));

        jPanel2.setBackground(new java.awt.Color(250, 240, 231));

        tab.setBackground(new java.awt.Color(254, 254, 254));
        tab.setFont(new java.awt.Font("Waree", 1, 15)); // NOI18N

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        homeButton.setActionCommand("homeButton");
        homeButton.setBackground(new java.awt.Color(101, 95, 123));
        homeButton.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(254, 254, 254));
        homeButton.setLabel("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton);

        eventButton.setActionCommand("eventButton");
        eventButton.setBackground(new java.awt.Color(101, 95, 123));
        eventButton.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        eventButton.setForeground(new java.awt.Color(254, 254, 254));
        eventButton.setLabel("Events");
        eventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventButtonActionPerformed(evt);
            }
        });
        jPanel1.add(eventButton);
        eventButton.getAccessibleContext().setAccessibleName("eventButton");

        groupButton.setActionCommand("groupButton");
        groupButton.setBackground(new java.awt.Color(101, 95, 123));
        groupButton.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        groupButton.setForeground(new java.awt.Color(254, 254, 254));
        groupButton.setLabel("Groups");
        groupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupButtonActionPerformed(evt);
            }
        });
        jPanel1.add(groupButton);
        groupButton.getAccessibleContext().setAccessibleName("groupButton");

        collectionButton.setActionCommand("collectionButton");
        collectionButton.setBackground(new java.awt.Color(101, 95, 123));
        collectionButton.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        collectionButton.setForeground(new java.awt.Color(254, 254, 254));
        collectionButton.setLabel("Collections");
        collectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectionButtonActionPerformed(evt);
            }
        });
        jPanel1.add(collectionButton);
        collectionButton.getAccessibleContext().setAccessibleName("collectionButton");

        tab.addTab("Main Tab", jPanel1);

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        globalRatings.setActionCommand("globalRatings");
        globalRatings.setBackground(new java.awt.Color(101, 95, 123));
        globalRatings.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        globalRatings.setForeground(new java.awt.Color(254, 254, 254));
        globalRatings.setLabel("Global  Ratings");
        globalRatings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                globalRatingsActionPerformed(evt);
            }
        });
        jPanel3.add(globalRatings);
        globalRatings.getAccessibleContext().setAccessibleName("globalRatings");

        groupCollection.setActionCommand("groupCollection");
        groupCollection.setBackground(new java.awt.Color(101, 95, 123));
        groupCollection.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        groupCollection.setForeground(new java.awt.Color(254, 254, 254));
        groupCollection.setLabel("Group Collection");
        groupCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupCollectionActionPerformed(evt);
            }
        });
        jPanel3.add(groupCollection);
        groupCollection.getAccessibleContext().setAccessibleName("groupCollection");

        recommendedGames.setActionCommand("recommendedGames");
        recommendedGames.setBackground(new java.awt.Color(101, 95, 123));
        recommendedGames.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        recommendedGames.setForeground(new java.awt.Color(254, 254, 254));
        recommendedGames.setLabel("Recommend Games");
        recommendedGames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recommendedGamesActionPerformed(evt);
            }
        });
        jPanel3.add(recommendedGames);

        gameNightRecommendation.setActionCommand("gameNightRecommendation");
        gameNightRecommendation.setBackground(new java.awt.Color(101, 95, 123));
        gameNightRecommendation.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        gameNightRecommendation.setForeground(new java.awt.Color(254, 254, 254));
        gameNightRecommendation.setLabel("Game Night");
        gameNightRecommendation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameNightRecommendationActionPerformed(evt);
            }
        });
        jPanel3.add(gameNightRecommendation);
        gameNightRecommendation.getAccessibleContext().setAccessibleName(" Game Night");

        tab.addTab("\"Unique\"", jPanel3);

        userComboBox.setBackground(new java.awt.Color(254, 254, 254));
        userComboBox.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        userComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "rnkambara@mix.wvu.edu", "adentrekin@mix.wvu.edu", "arMccalley@mix.wvu.edu" }));

        jLabel1.setFont(new java.awt.Font("Waree", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(101, 95, 123));
        jLabel1.setText("Select a User");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        tab.getAccessibleContext().setAccessibleName("mainTab");

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 250, 620));

        panel1.setBackground(new java.awt.Color(250, 240, 231));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCardboardCommunity.setFont(new java.awt.Font("Ubuntu Condensed", 0, 48)); // NOI18N
        labelCardboardCommunity.setForeground(new java.awt.Color(101, 95, 123));
        labelCardboardCommunity.setText("Cardboard Community");
        panel1.add(labelCardboardCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(101, 95, 123));
        panel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 223, 538, 12));
        panel1.add(cardboardCommunityIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 71, -1, 193));

        jSeparator2.setBackground(new java.awt.Color(101, 95, 123));
        panel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 241, 538, -1));
        panel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 450, 10));

        cbcIcon.setIcon(new javax.swing.ImageIcon("/home/rnkambara/Documents/CardBoard-Community/images/cardboard_community.png")); // NOI18N
        panel1.add(cbcIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));
        panel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 450, 10));
        panel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 450, 20));
        panel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 450, 20));

        add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 1270, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void groupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButtonActionPerformed
        Collection<Component> panels = null;
        String user = CardboardCommunity.form.getBasePanel().userComboBox.getSelectedItem().toString();
        try {
            panels = groupPanel.readPanels(CardboardCommunity.connection, "MEMBER_EMAIL = '" + user + "'");
            CardboardCommunity.form.getBasePanel().fillScrollableArea(panels);
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println("Oops");
        }

    }//GEN-LAST:event_groupButtonActionPerformed

    private void collectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectionButtonActionPerformed
        Collection<Component> panels = null;
        String user = CardboardCommunity.form.getBasePanel().userComboBox.getSelectedItem().toString();
        try {
            panels = CollectionPanel.readPanels(CardboardCommunity.connection, "USER_EMAIL = '" + user + "'");
            CardboardCommunity.form.getBasePanel().fillScrollableArea(panels);
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println("Oops");
        }
    }//GEN-LAST:event_collectionButtonActionPerformed

    private void eventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventButtonActionPerformed
      Collection<Component> panels = null;
      String user = CardboardCommunity.form.getBasePanel().userComboBox.getSelectedItem().toString();
        try {
            panels = EventPanel.readPanels(CardboardCommunity.connection, "ATTENDING_EMAIL = '" + user + "'");
            CardboardCommunity.form.getBasePanel().fillScrollableArea(panels);
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println("Oops");
        }
    }//GEN-LAST:event_eventButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
      CardboardCommunity.form.getBasePanel().fillScrollableArea(null);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void globalRatingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_globalRatingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_globalRatingsActionPerformed

    private void groupCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupCollectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_groupCollectionActionPerformed

    private void recommendedGamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recommendedGamesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recommendedGamesActionPerformed

    private void gameNightRecommendationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameNightRecommendationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameNightRecommendationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cardboardCommunityIcon;
    private javax.swing.JLabel cbcIcon;
    private java.awt.Button collectionButton;
    private java.awt.Button eventButton;
    private java.awt.Button gameNightRecommendation;
    private java.awt.Button globalRatings;
    private java.awt.Button groupButton;
    private java.awt.Button groupCollection;
    private java.awt.Button homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel labelCardboardCommunity;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private java.awt.Panel panel1;
    private java.awt.Button recommendedGames;
    private javax.swing.JPanel scrollPanelBox;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JComboBox<String> userComboBox;
    // End of variables declaration//GEN-END:variables
}
