/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cardboardcommunity;

import java.awt.Component;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;

/**
 *
 * @author rnkambara
 */
public class CollectionPanel extends javax.swing.JPanel {
    int game_id;
    int player_count;
    String name;
    String edition;
    String genre;
    int playtime;
    int rating;
    /**
     * Creates new form CollectionPanel
     */
    public CollectionPanel() {
        initComponents();
    }
    
     public void refresh(boolean showRating) throws SQLException
     {
         playerCountText.setText(player_count + "");
         labelBoardgame.setText(name);
         editionText.setText(edition);
         genreText.setText(genre);
         playtimeText.setText(playtime + "");
         if(!showRating)
         {
            ratingComboBox.setVisible(false);
            labelRating.setVisible(false);
         }
         else 
         {
            ratingComboBox.setSelectedIndex(rating);
            ratingComboBox.setVisible(true);
            labelRating.setVisible(true);
         }
     }
     
     public static Collection<Component> readPanels(Connection con, String whereClause) throws SQLException
     {
         Statement s1 = con.createStatement();
         s1.execute("SELECT B.GAME_ID, PLAYERCOUNT, NAME, EDITION, GENRE, PLAYTIME " 
                  + "FROM BOARD_GAME B, OWNERSHIP O " +
                    "WHERE " + whereClause + " AND B.GAME_ID = O.GAME_ID ");
         
         HashMap<Integer, Component> map = new HashMap<>();
         ResultSet groupRes = s1.getResultSet();
         
         while (groupRes.next())
         {
            CollectionPanel p = new CollectionPanel();
            p.game_id = groupRes.getInt("GAME_ID");
            p.player_count = groupRes.getInt("PLAYERCOUNT");
            p.name = groupRes.getString("NAME");
            p.edition = groupRes.getString("EDITION");
            p.genre = groupRes.getString("GENRE");
            p.playtime = groupRes.getInt("PLAYTIME");
            map.put(p.game_id, p);
        }
         
        for (Component p : map.values())
        {
           ((CollectionPanel)p).refresh(false);
        }
        return map.values();  
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        leftPanelOrange = new javax.swing.JPanel();
        labelDefaultImage = new javax.swing.JLabel();
        buttonRid = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        defaultBoardgameIcon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        labelBoardgame = new javax.swing.JTextArea();
        labelRating = new javax.swing.JLabel();
        labelPlayerCount = new javax.swing.JLabel();
        labelEdition = new javax.swing.JLabel();
        labelGenre = new javax.swing.JLabel();
        labelPlaytime = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        playerCountText = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        editionText = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        genreText = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        playtimeText = new javax.swing.JTextArea();
        ratingComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(101, 95, 123));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPanelOrange.setBackground(new java.awt.Color(233, 155, 2));
        leftPanelOrange.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        leftPanelOrange.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        leftPanelOrange.add(labelDefaultImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        buttonRid.setBackground(new java.awt.Color(233, 155, 2));
        buttonRid.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        buttonRid.setForeground(new java.awt.Color(254, 254, 254));
        buttonRid.setLabel("Rid");
        buttonRid.setName(""); // NOI18N
        buttonRid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRidActionPerformed(evt);
            }
        });
        leftPanelOrange.add(buttonRid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 80, 30));
        leftPanelOrange.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        defaultBoardgameIcon.setIcon(new javax.swing.ImageIcon("images/default_boardgame.png")); // NOI18N
        leftPanelOrange.add(defaultBoardgameIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(101, 95, 123));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(null);
        jScrollPane1.setEnabled(false);
        jScrollPane1.setOpaque(false);

        labelBoardgame.setBackground(new java.awt.Color(233, 155, 2));
        labelBoardgame.setColumns(20);
        labelBoardgame.setFont(new java.awt.Font("Waree", 1, 15)); // NOI18N
        labelBoardgame.setForeground(new java.awt.Color(254, 254, 254));
        labelBoardgame.setLineWrap(true);
        labelBoardgame.setRows(5);
        labelBoardgame.setText("Board Game");
        labelBoardgame.setWrapStyleWord(true);
        labelBoardgame.setBorder(null);
        jScrollPane1.setViewportView(labelBoardgame);

        leftPanelOrange.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 50));

        add(leftPanelOrange, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 230));

        labelRating.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        labelRating.setForeground(new java.awt.Color(253, 251, 251));
        labelRating.setText("Rating: ");
        add(labelRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 110, -1));

        labelPlayerCount.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        labelPlayerCount.setForeground(new java.awt.Color(253, 251, 251));
        labelPlayerCount.setText("Playercount: ");
        add(labelPlayerCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 140, -1));

        labelEdition.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        labelEdition.setForeground(new java.awt.Color(253, 251, 251));
        labelEdition.setText("Edition: ");
        add(labelEdition, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 110, -1));

        labelGenre.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        labelGenre.setForeground(new java.awt.Color(253, 251, 251));
        labelGenre.setText("Genre: ");
        add(labelGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 110, -1));

        labelPlaytime.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        labelPlaytime.setForeground(new java.awt.Color(253, 251, 251));
        labelPlaytime.setText("Playtime: ");
        add(labelPlaytime, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 110, -1));

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        playerCountText.setBackground(new java.awt.Color(254, 254, 254));
        playerCountText.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        playerCountText.setForeground(new java.awt.Color(112, 110, 110));
        playerCountText.setText("Player count here...");
        jScrollPane7.setViewportView(playerCountText);

        add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 200, 30));

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        editionText.setBackground(new java.awt.Color(254, 254, 254));
        editionText.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        editionText.setForeground(new java.awt.Color(112, 110, 110));
        editionText.setText("Edition here...");
        jScrollPane8.setViewportView(editionText);

        add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 200, 30));

        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        genreText.setBackground(new java.awt.Color(254, 254, 254));
        genreText.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        genreText.setForeground(new java.awt.Color(112, 110, 110));
        genreText.setText("Genre here...");
        jScrollPane9.setViewportView(genreText);

        add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 200, 30));

        jScrollPane10.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane10.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        playtimeText.setBackground(new java.awt.Color(254, 254, 254));
        playtimeText.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        playtimeText.setForeground(new java.awt.Color(112, 110, 110));
        playtimeText.setText("Playtime here...");
        jScrollPane10.setViewportView(playtimeText);

        add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 200, 30));

        ratingComboBox.setBackground(new java.awt.Color(254, 254, 254));
        ratingComboBox.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        ratingComboBox.setForeground(new java.awt.Color(112, 110, 110));
        ratingComboBox.setMaximumRowCount(6);
        ratingComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        add(ratingComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 200, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRidActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_buttonRidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonRid;
    private javax.swing.JLabel defaultBoardgameIcon;
    private javax.swing.JTextArea editionText;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextArea genreText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea labelBoardgame;
    private javax.swing.JLabel labelDefaultImage;
    private javax.swing.JLabel labelEdition;
    private javax.swing.JLabel labelGenre;
    private javax.swing.JLabel labelPlayerCount;
    private javax.swing.JLabel labelPlaytime;
    private javax.swing.JLabel labelRating;
    private javax.swing.JPanel leftPanelOrange;
    private javax.swing.JTextArea playerCountText;
    private javax.swing.JTextArea playtimeText;
    private javax.swing.JComboBox<String> ratingComboBox;
    // End of variables declaration//GEN-END:variables
}
