/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cardboardcommunity;

/**
 *
 * @author rnkambara
 */
public class CollectionPanel extends javax.swing.JPanel {

    /**
     * Creates new form CollectionPanel
     */
    public CollectionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanelOrange = new javax.swing.JPanel();
        labelDefaultImage = new javax.swing.JLabel();
        labelBoardgame = new javax.swing.JLabel();
        buttonRid = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        defaultBoardgameIcon = new javax.swing.JLabel();
        labelRating = new javax.swing.JLabel();
        labelPlayerCount = new javax.swing.JLabel();
        labelEdition = new javax.swing.JLabel();
        labelGenre = new javax.swing.JLabel();
        labelPlaytime = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(101, 95, 123));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPanelOrange.setBackground(new java.awt.Color(233, 155, 2));
        leftPanelOrange.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        leftPanelOrange.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        leftPanelOrange.add(labelDefaultImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        labelBoardgame.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        labelBoardgame.setForeground(new java.awt.Color(253, 251, 251));
        labelBoardgame.setText("Boardgame");
        leftPanelOrange.add(labelBoardgame, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        buttonRid.setBackground(new java.awt.Color(233, 155, 2));
        buttonRid.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        buttonRid.setForeground(new java.awt.Color(254, 254, 254));
        buttonRid.setLabel("Rid");
        buttonRid.setName(""); // NOI18N
        buttonRid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRidActionPerformed(evt);
            }
        });
        leftPanelOrange.add(buttonRid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 80, 30));
        leftPanelOrange.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        defaultBoardgameIcon.setIcon(new javax.swing.ImageIcon("/home/rnkambara/Documents/CardBoard-Community/images/default_boardgame.png")); // NOI18N
        leftPanelOrange.add(defaultBoardgameIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        add(leftPanelOrange, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 230));

        labelRating.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        labelRating.setForeground(new java.awt.Color(253, 251, 251));
        labelRating.setText("Rating: ");
        add(labelRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 110, -1));

        labelPlayerCount.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        labelPlayerCount.setForeground(new java.awt.Color(253, 251, 251));
        labelPlayerCount.setText("Playercount: ");
        add(labelPlayerCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 140, -1));

        labelEdition.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        labelEdition.setForeground(new java.awt.Color(253, 251, 251));
        labelEdition.setText("Edition: ");
        add(labelEdition, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 110, -1));

        labelGenre.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        labelGenre.setForeground(new java.awt.Color(253, 251, 251));
        labelGenre.setText("Genre: ");
        add(labelGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 110, -1));

        labelPlaytime.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        labelPlaytime.setForeground(new java.awt.Color(253, 251, 251));
        labelPlaytime.setText("Playtime: ");
        add(labelPlaytime, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 110, -1));

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setBackground(new java.awt.Color(254, 254, 254));
        jTextArea2.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(112, 110, 110));
        jTextArea2.setText("Player count here...");
        jScrollPane7.setViewportView(jTextArea2);

        add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 200, 30));

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea3.setBackground(new java.awt.Color(254, 254, 254));
        jTextArea3.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(112, 110, 110));
        jTextArea3.setText("Edition here...");
        jScrollPane8.setViewportView(jTextArea3);

        add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 200, 30));

        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea4.setBackground(new java.awt.Color(254, 254, 254));
        jTextArea4.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(112, 110, 110));
        jTextArea4.setText("Genre here...");
        jScrollPane9.setViewportView(jTextArea4);

        add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 200, 30));

        jScrollPane10.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane10.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea5.setBackground(new java.awt.Color(254, 254, 254));
        jTextArea5.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        jTextArea5.setForeground(new java.awt.Color(112, 110, 110));
        jTextArea5.setText("Playtime here...");
        jScrollPane10.setViewportView(jTextArea5);

        add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 200, 30));

        jComboBox1.setBackground(new java.awt.Color(254, 254, 254));
        jComboBox1.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(112, 110, 110));
        jComboBox1.setMaximumRowCount(6);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "1.0", "2.0", "3.0", "4.0", "5.0" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 200, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonRid;
    private javax.swing.JLabel defaultBoardgameIcon;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JLabel labelBoardgame;
    private javax.swing.JLabel labelDefaultImage;
    private javax.swing.JLabel labelEdition;
    private javax.swing.JLabel labelGenre;
    private javax.swing.JLabel labelPlayerCount;
    private javax.swing.JLabel labelPlaytime;
    private javax.swing.JLabel labelRating;
    private javax.swing.JPanel leftPanelOrange;
    // End of variables declaration//GEN-END:variables
}
