/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cardboardcommunity;

/**
 *
 * @author rnkambara
 */
public class groupPanel extends javax.swing.JPanel {

    /**
     * Creates new form groupPanel
     */
    public groupPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanelOrange = new javax.swing.JPanel();
        labelDefaultImage = new javax.swing.JLabel();
        labelGroupName = new javax.swing.JLabel();
        buttonWithdraw = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        labelMember = new javax.swing.JLabel();
        listMembers = new java.awt.List();
        labelLocation = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(101, 95, 123));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPanelOrange.setBackground(new java.awt.Color(25, 229, 198));
        leftPanelOrange.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        leftPanelOrange.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        leftPanelOrange.add(labelDefaultImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        labelGroupName.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        labelGroupName.setForeground(new java.awt.Color(253, 251, 251));
        labelGroupName.setText("Group Name");
        leftPanelOrange.add(labelGroupName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        buttonWithdraw.setBackground(new java.awt.Color(25, 229, 198));
        buttonWithdraw.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        buttonWithdraw.setForeground(new java.awt.Color(254, 254, 254));
        buttonWithdraw.setLabel("Withdraw");
        buttonWithdraw.setName(""); // NOI18N
        buttonWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWithdrawActionPerformed(evt);
            }
        });
        leftPanelOrange.add(buttonWithdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/rnkambara/Documents/cardboardCommunity/CardBoard-Community/images/default_group.jpeg")); // NOI18N
        leftPanelOrange.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        add(leftPanelOrange, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 230));

        labelMember.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        labelMember.setForeground(new java.awt.Color(253, 251, 251));
        labelMember.setText("Members");
        add(labelMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 110, -1));

        listMembers.setBackground(new java.awt.Color(254, 254, 254));
        listMembers.setFont(new java.awt.Font("Waree", 0, 12)); // NOI18N
        listMembers.setMultipleMode(true);
        listMembers.setName(""); // NOI18N
        listMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listMembersActionPerformed(evt);
            }
        });
        add(listMembers, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 320, 120));

        labelLocation.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        labelLocation.setForeground(new java.awt.Color(253, 251, 251));
        labelLocation.setText("Location: ");
        add(labelLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 140, -1));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 110, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 320, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWithdrawActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonWithdrawActionPerformed

    private void listMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listMembersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listMembersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonWithdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel labelDefaultImage;
    private javax.swing.JLabel labelGroupName;
    private javax.swing.JLabel labelLocation;
    private javax.swing.JLabel labelMember;
    private javax.swing.JPanel leftPanelOrange;
    private java.awt.List listMembers;
    // End of variables declaration//GEN-END:variables
}
