/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cardboardcommunity;
import java.sql.*;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
/**
 *
 * @author rnkambara
 */
public class groupPanel extends javax.swing.JPanel {
    int id;
    String name;
    String location;
    List<String> members;
    
    public void refresh(){
        
    }
    
    public static Collection<groupPanel> readPanels(Connection con, String whereClause) throws SQLException{
        Statement s = con.createStatement();
        s.addBatch("SELECT * FROM GROUP WHERE " + whereClause);
        s.addBatch("SELECT USER, GROUPID FROM MEMBERSHIP, (SELECT ID FROM GROUP WHERE " + whereClause + ") "
                + "WHERE GROUPID = ID"
        );
        s.executeBatch();
        HashMap<Integer, groupPanel> map = new HashMap<>();
        ResultSet groupRes = s.getResultSet();
        while (groupRes.next()){
            Integer id = groupRes.getInt("GROUPID");
            groupPanel p = new groupPanel();
            p.id = id;
            map.put(id, p);
            p.name = groupRes.getString("NAME");
            p.location = groupRes.getString("LOCATION");
            p.members = new ArrayList<String>();
        }
        s.getMoreResults();
        ResultSet memberRes = s.getResultSet();
        while (memberRes.next()){
            groupPanel p = map.get(memberRes.getInt("GROUPID"));
            p.members.add(memberRes.getString("membername")); //?
        }
        for (groupPanel p : map.values()){
            p.refresh();
        }
        return map.values();
    }
    
    /**
     * Creates new form groupPanel
     */
    public groupPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanelOrange = new javax.swing.JPanel();
        labelDefaultImage = new javax.swing.JLabel();
        labelGroupName = new javax.swing.JLabel();
        buttonWithdraw = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        defaultGroupIcon = new javax.swing.JLabel();
        labelMember = new javax.swing.JLabel();
        listMembers = new java.awt.List();
        labelLocation = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(101, 95, 123));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPanelOrange.setBackground(new java.awt.Color(25, 229, 198));
        leftPanelOrange.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        leftPanelOrange.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        leftPanelOrange.add(labelDefaultImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        labelGroupName.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        labelGroupName.setForeground(new java.awt.Color(253, 251, 251));
        labelGroupName.setText("Group Name");
        leftPanelOrange.add(labelGroupName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        buttonWithdraw.setBackground(new java.awt.Color(25, 229, 198));
        buttonWithdraw.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        buttonWithdraw.setForeground(new java.awt.Color(254, 254, 254));
        buttonWithdraw.setLabel("Withdraw");
        buttonWithdraw.setName(""); // NOI18N
        buttonWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWithdrawActionPerformed(evt);
            }
        });
        leftPanelOrange.add(buttonWithdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, 30));
        leftPanelOrange.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        defaultGroupIcon.setIcon(new javax.swing.ImageIcon("/home/rnkambara/Documents/CardBoard-Community/images/default_group.jpeg")); // NOI18N
        leftPanelOrange.add(defaultGroupIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        add(leftPanelOrange, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 230));

        labelMember.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        labelMember.setForeground(new java.awt.Color(253, 251, 251));
        labelMember.setText("Members");
        add(labelMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 110, -1));

        listMembers.setBackground(new java.awt.Color(254, 254, 254));
        listMembers.setFont(new java.awt.Font("Waree", 0, 12)); // NOI18N
        listMembers.setMultipleMode(true);
        listMembers.setName(""); // NOI18N
        listMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listMembersActionPerformed(evt);
            }
        });
        add(listMembers, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 320, 120));

        labelLocation.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        labelLocation.setForeground(new java.awt.Color(253, 251, 251));
        labelLocation.setText("Location: ");
        add(labelLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 140, -1));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 110, 10));

        jTextPane1.setBackground(new java.awt.Color(101, 95, 123));
        jTextPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 95, 123)));
        jTextPane1.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(254, 254, 254));
        jTextPane1.setText(" Rating Here...");
        jScrollPane1.setViewportView(jTextPane1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 200, 30));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setBackground(new java.awt.Color(254, 254, 254));
        jTextArea1.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(112, 110, 110));
        jTextArea1.setText("Location goes here...");
        jScrollPane3.setViewportView(jTextArea1);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 180, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWithdrawActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonWithdrawActionPerformed

    private void listMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listMembersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listMembersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonWithdraw;
    private javax.swing.JLabel defaultGroupIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel labelDefaultImage;
    private javax.swing.JLabel labelGroupName;
    private javax.swing.JLabel labelLocation;
    private javax.swing.JLabel labelMember;
    private javax.swing.JPanel leftPanelOrange;
    private java.awt.List listMembers;
    // End of variables declaration//GEN-END:variables
}
